display_name: CharacterBook
publisher_display_name: MaxGog
identity_name: 52304FeatherProjects.CBook
msix_version: 1.7.1.0
publisher: CN=B9003DCF-59B1-401C-9896-9F045D0A6C6D
logo_path: assets/iconapp.png
start_menu_icon_path: assets/iconapp.png
tile_icon_path: assets/iconapp.png
capabilities: internetClient
architecture: x64
install_mode: allow_elevation